// main.cpp - Verilator Driver & Verification Testbench
#include <iostream>
#include <vector>
#include <memory>
#include <cassert>
#include "Vsimd_compute_unit.h"  // Generated by Verilator
#include "verilated.h"

// Golden C++ Model for Verification
class GoldenSIMDModel {
public:
    uint32_t vregs[32][8];
    uint8_t  vmask = 0xFF; // All 8 lanes active by default

    void execute_vadd(int vd, int vs1, int vs2) {
        for (int lane = 0; lane < 8; ++lane) {
            if (vmask & (1 << lane)) {
                vregs[vd][lane] = vregs[vs1][lane] + vregs[vs2][lane];
            }
        }
    }
};

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    auto top = std::make_unique<Vsimd_compute_unit>();
    GoldenSIMDModel golden;

    // Reset Sequence
    top->clk = 0;
    top->reset = 1;
    top->eval();
    top->clk = 1;
    top->eval();
    top->reset = 0;

    std::cout << "[CPP Testbench] SIMD Compute Unit Initialization Complete." << std::endl;

    // Simulation Loop Example
    vluint64_t main_time = 0;
    while (!Verilated::gotFinish() && main_time < 200) {
        top->clk = !top->clk;
        top->eval();

        // Feed test inputs on rising clock edge
        if (top->clk == 1 && main_time == 10) {
            std::cout << "[CPP Testbench] Triggering Vector Addition Test..." << std::endl;
            // Send instruction signal to top module interface
        }

        main_time++;
    }

    std::cout << "[CPP Testbench] Simulation Finished Successfully." << std::endl;
    return 0;
}